spring:
  application:
    name: bookstore-user-service
server:
  port: 8080

app:
  messaging:
    enabled: ${APP_MESSAGING_ENABLED:true}
    exchange-events: ${APP_MESSAGING_EXCHANGE_EVENTS:bookstore.events}
    queue-password-reset: ${APP_MESSAGING_QUEUE_PASSWORD_RESET:notification.password_reset_events}
    rk-password-reset: ${APP_MESSAGING_RK_PASSWORD_RESET:user.password_reset}
    otp-expiry-minutes: ${APP_MESSAGING_OTP_EXPIRY_MINUTES:5}
