spring:
  application:
    name: bookstore-user-service
server:
  port: 8080

app:
  oauth:
    google:
      client-id: ${GOOGLE_CLIENT_ID:}
      client-secret: ${GOOGLE_CLIENT_SECRET:}
      redirect-uri: ${GOOGLE_REDIRECT_URI:}
      frontend-redirect-url: ${GOOGLE_FRONTEND_REDIRECT_URL:http://localhost:3000}
  messaging:
    enabled: ${APP_MESSAGING_ENABLED:true}
    exchange-events: ${APP_MESSAGING_EXCHANGE_EVENTS:bookstore.events}
    queue-password-reset: ${APP_MESSAGING_QUEUE_PASSWORD_RESET:notification.password_reset_events}
    rk-password-reset: ${APP_MESSAGING_RK_PASSWORD_RESET:user.password_reset}
    otp-expiry-minutes: ${APP_MESSAGING_OTP_EXPIRY_MINUTES:5}
    email-verification-base-url: ${APP_EMAIL_VERIFICATION_BASE_URL:http://localhost:8080}
