apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  DB_HOST: "bookstore-db-do-user-36177370-0.h.db.ondigitalocean.com"
  DB_PORT: "25060"
  DB_NAME: "bookstore_user"
  SPRING_DATA_REDIS_HOST: "redis-bookstore-do-user-36177370-0.j.db.ondigitalocean.com"
  SPRING_DATA_REDIS_PORT: "25061"
  SPRING_DATA_REDIS_USERNAME: "default"
  SPRING_DATA_REDIS_SSL_ENABLED: "true"
  RABBITMQ_HOST: "143.198.204.41"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VIRTUAL_HOST: "bookstore"
  APP_MESSAGING_EXCHANGE_EVENTS: "bookstore.events"
  APP_MESSAGING_QUEUE_PASSWORD_RESET: "notification.password_reset_events"
  APP_MESSAGING_RK_PASSWORD_RESET: "user.password_reset"
  APP_MESSAGING_OTP_EXPIRY_MINUTES: "5"
  GOOGLE_REDIRECT_URI: "https://nhasachcongdong.id.vn/api/auth/google/callback"
  GOOGLE_FRONTEND_REDIRECT_URL: "https://nhasachcongdong.id.vn"
  APP_JWT_EXPIRATION_MS: "86400000"
  APP_JWT_REFRESH_EXPIRATION_MS: "604800000"
